function __pkg_query_help
    printf "\nPlease specify package(s) or option\n"
    printf "If there are no option provided, it will run pacman -Qs\n"
    printf "which is will search from installed packages.\n"
    printf "\nQuery options:\n\n"
    printf "    e, explicit\t\t: List all explicitly installed packages\n"
    printf "\t\t\t  (installed from the sync database(s)).\n"
    printf "    en\t\t\t: List all explicitly installed native packages.\n"
    printf "    f, foreign\t\t: List all foreign packages\n"
    printf "\t\t\t  (installed from outside the sync database(s)).\n"
    printf "    g, group \e[3;32mgroup\e[0m\t: List all packages "
    printf "in the package group named \e[3;32mgroup\e[0m.\n"
    printf "    i, info \e[3;32mpkgs\e[0m\t: Display info "
    printf "of installed package(s) named \e[3;32mpkgs\e[0m.\n"
    printf "    l, latest \e[3;32mN\e[0m\t\t: List the \e[3;32mN\e[0m"
    printf "(default: 20) last installed packages.\n"
    printf "    n, native\t\t: List all native packages\n"
    printf "\t\t\t  (installed from the sync database(s)).\n"
    printf "    u, unused\t\t: List all unused packages (orphans).\n\n"
end
